//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerSessions
    {
        public int PackageId { get; set; }
        public int TrainerId { get; set; }
        public System.DateTime SessionDateTime { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual TrainingPackages TrainingPackages { get; set; }
    }
}
