//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingPackages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingPackages()
        {
            this.TrainerSessions = new HashSet<TrainerSessions>();
        }
    
        public int PackageId { get; set; }
        public int SubscriptionId { get; set; }
        public int TrainerId { get; set; }
        public int RemainingSessions { get; set; }
        public System.DateTime PurchaseDate { get; set; }
    
        public virtual Subscriptions Subscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerSessions> TrainerSessions { get; set; }
    }
}
